version: '3.7'
services:
  spring-boot-app_dev:
    build:
      context: .
#      args:
#        KEYSTORE_LOCATION: /app/keystore.p12
    ports:
      - "8089:8088"
    networks:
      - db_network


networks:
  db_network:
    driver: bridge