version: '3.7'
services:
  spring-boot-app_dev:
    build:
      context: .
#      args:
#        KEYSTORE_LOCATION: /app/keystore.p12
    ports:
      - "10.100.40.14:8088:8088"
    volumes:
      - ./media/otp_images/images:/media/otp_images/images
    networks:
      - db_network


networks:
  db_network:
    driver: bridge