server:
  port: 8088
  servlet:
    context-path: /api
#  ssl:
#    key-store-type: PKCS12
#    key-store: ${KEYSTORE_LOCATION}
    #    key-store: file:///C:/Users/Lenovo/Desktop/projects/estate/estate/keystore.p12
#    key-store-password: otpproject
#    key-alias: otpproject


datasource:
  url: jdbc:postgresql://10.100.40.2:5442/biosecurity-boot
  username: root
  password: 2sgQc4cM

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  jackson:
    time-zone: UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    debug: true

  redis:
    host: redis
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
    cache:
      type: lettuce

  datasource:
#    url: jdbc:postgresql://postgres2:5432/otp_db #--for server
    url: jdbc:postgresql://postgres2:5432/public #--for local
    username: OtpUser
    password: Otp@10934!PasswAA
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: public

  jpa:
    properties:
      hibernate.default_schema: public
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

otp:
  testjson: test-users.json
  token:
    expired-in: 1440

jwt:
  salt: ThisIssalT00019127324353
  secret: thisissecret
  expires: 30000000

filestorage:
  path: media/otp_images/images
