server:
  port: 8088
  servlet:
    context-path: /api

datasource:
  url: jdbc:postgresql://10.100.40.2:5442/biosecurity-boot
  username: root
  password: 2sgQc4cM

spring:
  jackson:
    time-zone: UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    debug: true
  datasource:
#    url: jdbc:postgresql://postgres2:5432/otp_db #--for server
    url: jdbc:postgresql://localhost:5432/otp_db #--for local
    username: javidan
    password: javidan
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: otp_db

  jpa:
    properties:
      hibernate.default_schema: otp_db
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

otp:
  testjson: test-users.json
  token:
    expired-in: 1440

jwt:
  salt: ThisIssalT00019127324353
  secret: thisissecret
  expires: 30000000
